use_frameworks!

target 'RxStoreKit_Example' do
  pod 'RxStoreKit', :path => '../'

  target 'RxStoreKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
